= https://github.com/CWACoderWithAttitude/dc-startrek[dc-startrek]
:source-highlighter: coderay

== TL;DR
Container based python development. Ships with https://www.postgresql.org[postgreSQL DB] and https://github.com/wodby/adminer[adminer].
VSC setup contains some plugins and settings in link:./.devcontainer/devcontainer.json[devcontainer.json]

== Components

=== FastAPI
FastAPI is used to provide the REST API to manage Chuck Norris quotes.
The demo app was build TDD style. Coverage is currently at ~95%.
On devcontainer startup `ptw` test listener is started.


=== PostgreSQL
Current values for credentials, db name and external db port can be set in 
[source,%linenums,text,highlight=1-5]
include::./.devcontainer/.env[]

=== Postgres Monitoring
Added monitoring Postgres with `wrouesnel/postgres_exporter`. AToW there is no dashboard in grafa to visualize the data.
Metrics are scraped by prometheus on http://localhost:9187/metrics.

=== Adminer
Adminer is used to peek into the database.

=== Prometheus
Prometheus will collect application metrics.
Default config is shipped with this setup. 
Please refer to file://./.devcontainer/prometheus_data/prometheus.yml[prometheus.yml] for details.


=== Grafana
Is used to visualize the metrics collected by Prometheus.
To use it:
1. add prometheus connection to http://prometheus:9090, test and save
2. add dashboard by importing dashboard `18739` from grafana website.

=== Loggin
https://medium.com/@netopschic/implementing-the-log-monitoring-stack-using-promtail-loki-and-grafana-using-docker-compose-bcb07d1a51aa
https://github.com/xente/loki-logger-handler
https://grafana.com/docs/loki/latest/send-data/
https://grafana.com/docs/alloy/latest/tutorials/send-logs-to-loki/

== Links
* http://localhost:9690/targets[Prometheus Targets]
* http://localhost:9630/connections/datasources/edit/defqw6dierj7ke[Grafana Datasource] (admin/admin)
* http://localhost:9600/ship/[FastAPI Chuck Norris Quotes]
* http://localhost:9610/?pgsql=db&username=star&password=trek&db=star-trek-ships-db[Adminer Startrek Ships DB]
* OAuth2 implementation as outlined in https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/#update-the-dependencies[FastAPI OAuth2 JWT] on fastapi.tiangolo.com

== How 2 use
First of all we need to add you sourcecode to the container setup.   
Diffent ways:
1. Copy the source code to this projects root folder
2. Setup the path to your sourcecode in `.env`.
[source,%linenums,text,highlight=10]
include::./.devcontainer/.env[]

== Monitoring
* https://kubernetestraining.io/blog/fastapi-prometheus-monitoring[Instrumenting FastAPI Apps with Prometheus Metrics]
* https://dev.to/ken_mwaura1/getting-started-monitoring-a-fastapi-app-with-grafana-and-prometheus-a-step-by-step-guide-3fbn[Getting Started: Monitoring a FastAPI App with Grafana and Prometheus - A Step-by-Step Guide]

== OAuth2-Hints
Currently there's no UI to add users to the application.
To add a user to the application you can use the following code:
```
>>> from passlib.context import CryptContext
>>> pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
>>> pwd_context.hash("Example1!")
'$2b$12$XSeIVJPWjKQvfoP2I/9pXe6FMPpIRYA55Xr.T613A2kZWDvRl5DWm'
>>> 
```

== Dev Tips
As i began moving towards https://docs.astral.sh/uv/[uv] to manage my projects i will keep track of steps i take.
Where feasable i will try to follow tips by https://www.youtube.com/watch?v=jxqGsJEhiAg[arjan.codes]


=== Create project from existing stuff
[source,shell]
----
vscode ➜ /src (main) $ uv init
----

=== Split application from dev dependencies
I'll just delete all dev stuff from `requirements.txt` and readd dev dependencies to `pyproject.toml`.
[source,shell]
----
vscode ➜ /src (main) $ uv add --dev pytest pytest-watch
Resolved 38 packages in 342ms
Audited 37 packages in 0.04ms
----


