###
# Create a simple ship
@port=9600
POST http://localhost:{{port}}/ship/
Content-Type: application/json

{
    "name": "USS Franklin",
    "sign": "NX-326",
    "classification": "Starship"
}

###
# Create a full ship
@port=9600
POST http://localhost:{{port}}/ship/
Content-Type: application/json

{
    "name": "USS Franklin",
    "sign": "NX-326",
    "classification": "Starship",
    "speed": "Warp 4",
    "captain": "balthazar edison",
    "comment": "lost ~2160, first warp 4 capable ship",
    "url":"https://memory-alpha.fandom.com/wiki/Star_Trek:_The_Next_Generation"
}

###
# get all ships
###
GET http://localhost:9600/ship

?? status == 200

###
# Patch a quote

PUT http://localhost:{{port}}/ship/2
Content-Type: application/json

{
    "name": "USS Daunbtless.PUT2", "classification": "german.PUT2", "sign": "NCC-80816.PUT2"
}

?? status == 200
###
# Create a list of quotes
POST http://localhost:{{port}}/chuck_norris/
Content-Type: application/json

[
    {
    "quote": "Chuck Norris kann Drehtüren zuschlagen.", "language": "german"
    },
    {
    "quote": "Chuck Norris kann Drehtüren zuschlagen.", "language": "german"
    },
    {
    "quote": "Chuck Norris kann Drehtüren zuschlagen.", "language": "german"
    }
]

?? status == 201

###
# get just 5 chuck norris quotes
###
GET http://localhost:{{port}}/chuck_norris?limit=2

?? status == 200
###
# get specific ship by id
###
GET http://localhost:9600/ship/1

?? status == 500
###
# get just a specific chuck norris quote by id
###
GET http://localhost:9600/default_ships

?? status == 200

###
# DELETE a specific chuck norris quote by id
###
DELETE http://localhost:{{port}}/chuck_norris/1

?? status == 204