###
# Create a simple ship
@port=9600
@host=localhost
POST http://{{host}}:{{port}}/ship/
Content-Type: application/json

{
    "name": "USS Franklin",
    "sign": "NX-326",
    "classification": "Starship"
}


# Create a full ship
POST http://{{host}}:{{port}}/ship/
Content-Type: application/json

{
    "name": "USS Franklin",
    "sign": "NX-326",
    "classification": "Starship",
    "speed": "Warp 4",
    "captain": "balthazar edison",
    "comment": "lost ~2160, first warp 4 capable ship",
    "url":"https://memory-alpha.fandom.com/wiki/Star_Trek:_The_Next_Generation"
}

###
# get all ships
###
GET http://{{host}}:{{port}}/ship

?? status == 200

###
# Update a ship

PUT http://{{host}}:{{port}}/ship/2
Content-Type: application/json

{
    "name": "USS Daunbtless.PUT2", "classification": "german.PUT2", "sign": "NCC-80816.PUT2"
}
?? status == 200

###
# retrieve a certain number of ships
###
GET http://{{host}}:{{port}}/ship?limit=3

?? status == 200
###
# get specific ship by id
###
GET http://{{host}}:{{port}}/ship/1

?? status == 500
###
# get just a specific chuck norris quote by id
###
GET http://{{host}}:{{port}}/default_ships

?? status == 200

###
# DELETE an existing ship (before ensure that the ship exists)
###
DELETE http://{{host}}:{{port}}/ship/2

?? status == 204
###
# DELETE an existing ship (before ensure that the ship exists)
###
DELETE http://{{host}}:{{port}}/ship/1234567890

?? status == 404