services:
  dc-startrek:
    container_name: dc-startrek
    hostname: dc-startrek.local
    env_file:
      - .env
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    ports:
      - "${app_port}:8000"
      - "${streamlit_app_port}:8501"
    depends_on:
      - loki
    networks:
      dc-startrek-net:
    #depends_on:
    #  - db

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"    
    networks:
      - dc-startrek-net
  db:
  #image: postgres:17.4-alpine3.21
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${db_user} #postgres
      - POSTGRES_PASSWORD=${db_password} #postgres
      - POSTGRES_DB=${db_name} #fritzbox
    ports:
      - "${db_port}:5432"
    networks:
      dc-startrek-net:
    volumes:
     - db_data_chuck_norris14:/var/lib/postgresql/data
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    restart: always
    ports:
      - ${postgres_exporter_port}:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://${db_user}:${db_password}@db:5432/${db_name}?sslmode=disable
    networks:
      dc-startrek-net:
    depends_on:
      - db
  adminer:
    image: adminer:5.0.4
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_HTTP_EXTERN}:8080
    depends_on:
      - db
    networks:
      dc-startrek-net:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - ${prometheus_port}:9090
    volumes:
      - ./prometheus_data/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      dc-startrek-net:
  #depends_on:
  #  - dc-startrek

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - ${grafana_port}:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      dc-startrek-net:
    depends_on:
       - prometheus
       - loki

networks:
  dc-startrek-net:
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data
  db_data_chuck_norris14: 
    driver: local
    #driver_opts:
    #  o: bind
    #  type: none
    #  device: ./db_data_chuck_norris


